name: Fork Repository
on:
  push: #initially create the workflow when we first do our git push, otherwise, we will get a 404 NOT FOUND error when we first invoke the workflow API
  workflow_dispatch:
    inputs:
      owner:
        description: 'Repository Owner'     
        required: true
      repo:
        description: 'Repository'     
        required: true
      fork-org:
        description: 'Fork organization'     
        required: true
jobs:
  fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fork repository
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const owner = ${{ github.event.inputs.owner }};
            const repo = ${{ github.event.inputs.repo }};
            const org = ${{ github.event.inputs.fork-org }};
            const name = `${owner}-${repo}`;

            async function forkRepo() {
              try {
                const response = await github.repos.createFork({
                  owner: owner,
                  repo: repo,
                  organization: org,
                  name: name
                });
                console.log(`Repository ${response.data.full_name} forked to organization ${org}`);
              } catch (error) {
                console.error('Failed to fork repository:', error);
              }
            }

            forkRepo();
